awesome:
  pizza:
    api:
      name: Awesome Pizza
      version: 0.0.1

server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    org:
      altervista:
        breve:
          awesome:
            pizza: DEBUG