awesome:
  pizza:
    api:
      name: Awesome Pizza
      version: 0.0.1

server:
  error:
    include-message: always

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/awesome-pizza-mongo

logging:
  level:
    root: INFO
    org:
      altervista:
        breve:
          awesome:
            pizza: DEBUG